resources = Resource.create([


{nid: 112, tnid: 112,
 language: '1',
 title: 'Business Planning for Sustainability: Community Technology Center Planning & Implementation Handbook',
 body: '<P>This is the community technology center (CTC) handbook. It is part of WIT*777*s Business Planning for Sustainability Curriculum.</P>',
 focus_women: 1,
 is_featured: true,
 orgname: 'Institute of International Education (IIE)',
 mepi_project: 'Women in Technology (WIT)',
 number_pages: 71,
 },

    {nid: 408, tnid: 408,
     language: '1',
     title: 'Entrepreneurship Training Participant Manual',
     body: '<P>The manual gives overviews, materials and homework for six sessions: laying the foundation, marketing basics, marketing strategy/cost of business, financial concepts, financing business and summation and vision. This is part of WIT*777*s Entrepreneurship Training.</P>',
     focus_women: 1,
     orgname: 'Institute of International Education (IIE)',
     mepi_project: 'Women in Technology (WIT)',
     training_event: '',
     presenter: '',
     partner_orgs: '',
     materialtype_id: 3,
     number_pages: 100,
     is_featured: true,
     website: '' },

    {nid: 557, tnid: 557,
     language: '1',
     title: 'Identifying Women*777*s Challenges and Needs in Rural Communities ',
     body: '<p>This presentation addresses the issue of development in rural communities, with a special focus on gender issues.</p>',
     focus_women: 1,
     orgname: 'American Near East Refugees Aid (ANERA)',
     mepi_project: 'Empowering Women*777*s Community Based Organizations in Jordan',
     training_event: '',
     presenter: '',
     partner_orgs: '',
     is_featured: true,
     materialtype_id: 5,
     number_pages: 57,
     website: '' },

    {nid: 620, tnid: 620,
     language: '1',
     title: 'The Communication Process',
     body: '<P>This presentation covers interpersonal communication in a broad sense. It explains interpersonal communications in terms of messenger, message and audience, and how all three relate to each other.</P>',
     orgname: 'Business Care Consulting',
     mepi_project: 'Principles of Writing for the Web Effectively',
     training_event: '',
     presenter: '',
     partner_orgs: '',
     materialtype_id: 5,
     is_featured: true,
     number_pages: 20,
     website: '' },

    {nid: 1170, tnid: 1170,
     language: '1',
     title: 'The Role of School Journalism in Enhancing Democratic Awareness',
     body: '<p>This instructor*777*s curriculum presentation for educators focuses on the role of school journalism in enhancing democratic awareness. The curriculum includes six topics related to journalism in schools: introduction to journalism; the art of media in educational activity; journalism investigation; editing; press management and editing; and radio broadcasting skills.</p>',
     orgname: 'The Center for International Humanitarian Law & Human Rights',
     mepi_project: 'School of Journalism & Raising Democratic Awareness',
     training_event: 'The Role of School Journalism in Enhancing Democratic Awareness workshop',
     event_date: DateTime.new(2010,5,01),
     presenter: '',
     partner_orgs: '',
     is_featured: true,
     materialtype_id: 5,
     number_pages: 94,
     website: '' }
                            ])