orgs = Organization.create([

                               {name: ' مركز الدراسات و الاعلام الاقتصادي'},
                               {name: ' International Research and Exchanges Board (IREX)'},
                               {name: ' مركز الدراسات و الاعلام الاقتصادي'},
                               {name: 'Academy for Education Development (AED)'},
                               {name: 'Academy for Educational Development (AED)'},
                               {name: 'Additional MEPI-Funded Resources'},
                               {name: 'Additional Relevant Resources'},
                               {name: 'AIESEC'},
                               {name: 'American Bar Association'},
                               {name: 'American Bar Association (ABA)'},
                               {name: 'American Federation of Teachers'},
                               {name: 'American Federation of Teachers (AFT)'},
                               {name: 'American Near East Refugees Aid (ANERA)'},
                               {name: 'Arab Center for the Development of the Rule of Law and Integrity (ACRLI)'},
                               {name: 'Arab Foundation for Development and Citizenship'},
                               {name: 'Booz Allen Hamilton'},
                               {name: 'Business Care Consulting'},
                               {name: 'Center for Democracy & Election Management (CDEM), American University'},
                               {name: 'Center for International Private Enterprise (CIPE)'},
                               {name: 'CHF International'},
                               {name: 'Creative Associates'},
                               {name: 'Creative Associates International'},
                               {name: 'Da**em for Media'},
                               {name: 'Daem For Media'},
                               {name: 'Democracy International'},
                               {name: 'EL Sadat Association for Social Development and Welfare'},
                               {name: 'Family Social Association for Development (FAD)'},
                               {name: 'Financial Services Volunteer Corp (FSVC)'},
                               {name: 'Financial Services Volunteer Corps'},
                               {name: 'Financial Services Volunteer Corps (FSVC)'},
                               {name: 'Financial Servies Volunteer Corps (FSVC)'},
                               {name: 'Foundation for the Defense of Democracies (FDD)/Center for Liberty in the Middle East (CLIME)'},
                               {name: 'Freedom House '},
                               {name: 'Global Rights'},
                               {name: 'Google Analytics'},
                               {name: 'Higher Education for Development (HED)'},
                               {name: 'ICF International'},
                               {name: 'ICF International, Vital Voices Global Partnership'},
                               {name: 'Institute for Social and Economic Development (ISED) Solutions'},
                               {name: 'Institute for War & Peace Reporting (IWPR)'},
                               {name: 'Institute of International Education'},
                               {name: 'Institute of International Education (IIE)'},
                               {name: 'International Center for Not-for-Profit Law (ICNL)'},
                               {name: 'International Foundation for Election Systems (IFES)'},
                               {name: 'International Republican Institute (IRI)'},
                               {name: 'International Research & Exchanges Board (IREX)'},
                               {name: 'International Research and Exchanges Board (IREX)'},
                               {name: 'IREX'},
                               {name: 'ISED Solutions'},
                               {name: 'Johns Hopkins University School of Advanced International Studies'},
                               {name: 'Keshev - The Center for the Protection of Democracy in Israel'},
                               {name: 'Lebanese American University'},
                               {name: 'Media Women Forum (MFW)'},
                               {name: 'MEPI Lebanon Alumni Association'},
                               {name: 'Mercy Corps'},
                               {name: 'National Conference of State Legislatures (NCSL) '},
                               {name: 'National Democratic Institute '},
                               {name: 'National Democratic Institute (NDI)'},
                               {name: 'Near East Foundation'},
                               {name: 'Online Activism Institute'},
                               {name: 'Open Learning Center for Training & Consultation'},
                               {name: 'Organization for Promoting Integrity (OPI) '},
                               {name: 'Partners for Democratic Change'},
                               {name: 'Rady School of Management, University of California, San Diego'},
                               {name: 'Scholastic'},
                               {name: 'Society Voice Foundation'},
                               {name: 'Solidarity Center'},
                               {name: 'Soliya'},
                               {name: 'SOUL For Development'},
                               {name: 'Studies and Economic Media Center (SEMC) '},
                               {name: 'Tamkeen Development Foundation (TDF) '},
                               {name: 'The Center for International Humanitarian Law & Human Rights'},
                               {name: 'Think Media Labs'},
                               {name: 'U.S. Department of Commerce'},
                               {name: 'United Nations'},
                               {name: 'United States Department of Agriculture (USDA)'},
                               {name: 'University of Delaware'},
                               {name: 'Vital Voices'},
                               {name: 'Vital Voices Global Partnership'},
                               {name: 'Wi**am: Palestinian Conflict Resolution & Transformation Center'},
                               {name: 'World Learning'},
                               {name: 'World Mountain People Association Morocco (WMPA Morocco)'},
                               {name: 'Yemeni National Forum for Human Rights (NFHR) '},
                               {name: 'YWCA Lebanon'},
                               {name: 'المنظمة اليمنية لتعزيز النزاهة '},
                               {name: 'جمعية الأسرة الاجتماعية للتنمية '},
                               {name: 'داعم  للاعلام '},
                               {name: 'مجلس الأبحاث والتبادل الدولي -آيركس'},
                               {name: 'مجلس الأبحاث والتبادل الدولي-آيركس'},
                               {name: 'مركز التعليم المفتوح للتدريب والاستشارات'},
                               {name: 'مركز داعم لتدريب وحرية الإعلام'},
                               {name: 'مركز وئام'},
                                  {name: 'Center for International Humanitarian Law & Human Rights (CIHLHR)'},

                           ])