projects = Project.create([
{name: 'ABA Rule of Law Initiative (ABA ROLI)'},
  {name: 'Advancing Civic Engagement in Tunisia and Global Citizen Corps (GCC)'},
  {name: 'Algeria Partnership Schools Program'},
  {name: 'Bankruptcy Reform'},
  {name: 'Breaking Barriers: Empowering Women in the Workforce'},
  {name: 'Building a Modern System of Corporate Governance'},
  {name: 'Building Inclusive Democratic Institutions'},
  {name: 'Building Public-Private Partnerships for Women*777*s Advancement - MENA Businesswomen*777*s Network'},
  {name: 'Building Working Women*777*s Political and Social Participation in Jordan'},
{name: 'Civic Education Partnership Initiative'},
{name: 'Civil Society Law Reform'},
{name: 'Commercial Law Development Program (CLDP)'},
{name: 'Community Involvement in Reforming Primary Education'},
{name: 'Community Monitoring for Local Councils '},
{name: 'Democracy and Community  Development Program'},
{name: 'E-Mediat'},
{name: 'Empowering Women*777*s Community Based Organizations in Jordan'},
  {name: 'Enhance Women*777*s Leadership and Civic Democratic Participation: Campaining to Stop Honor Killings'},
{name: 'Enhancing CSO National Dialogue and Collaboration via Social Media'},
{name: 'Enhancing Transparency in Political Finance in the Arab Region'},
{name: 'Establishing Student Councils'},
{name: 'Expanding Support for Political Reform'},
{name: 'Family Law and the Kuwaiti Parliamentary '},
{name: 'Gulf States Electoral Initiatives Program'},
{name: 'Human Rights Education Program for Women in Morocco'},
{name: 'Improving the Services Provided by Microfinance Institutions'},
{name: 'Inheritance Denied: Combating Gender Inequality in Property Rights in Palestine'},
{name: 'Legal and Judicial Development in Algeria'},
{name: 'Legal and Judicial Development in Morocco'},
{name: 'Libya Elections Reporting Network'},
{name: 'Local Engagement for Advocacy and Dialogue (LEAD)'},
{name: 'MEFTA Technical Assistance-USDA'},
{name: 'MENA Businesswomen*777*s Network'},
  {name: 'Middle East and North Africa Regional Campaign Schools Program'},
  {name: 'Middle East Entrepreneur Training Program in the U.S. (MEET U.S.)'},
  {name: 'My Arabic Library'},
  {name: 'NGOs in the Mountain & Good Governance'},
  {name: 'Oncology Nursing Modules'},
  {name: 'Online Activism Institute'},
  {name: 'Operating for Impact: Improving the Efficacy of CSOs in Bahrain'},
  {name: 'Parliamentary Staff Training and Technical Assistance in North Africa and Lebanon '},
  {name: 'Partnership for Financial Excellence '},
  {name: 'Partnership for Financial Excellence IV'},
  {name: 'Partnership School Project in Oman (and the Middle East)'},
  {name: 'Policy Advocates for Women*777*s Issues '},
{name: 'Principles of Writing for the Web Effectively'},
{name: 'Programme de Développement de Droit Commercial'},
{name: 'Projet du développement des capacités axées sur les résultats (ROCCD)'},
{name: 'Promoting Citizenship to Engage Arab Youth'},
{name: 'Promoting Education, Altruism, and Civic Engagement (PEACE)'},
{name: 'Qatar Civic Education'},
{name: 'Reading and Understanding Legislation'},
{name: 'Results Oriented Commercial-Organization Capacity Development (ROCCD) Project'},
{name: 'ROCCD (Results-Oriented Commercial Capacity Development) Project'},
{name: 'Rule of Law Initiative - Qatar '},
{name: 'School of Journalism & Raising Democratic Awareness'},
{name: 'SIT Inspector Courses - Algeria'},
{name: 'Social Media | Social Action for Good Governance'},
{name: 'Social Media, Social Action'},
{name: 'Strengthen Political Parties and Improve the Transparency of Electoral Systems in North Africa'},
{name: 'Strengthening the Rule of Law in Lebanon through Rights Education'},
{name: 'Strengthening Women and Youth Voices in Political Participation during the Transition Period'},
{name: 'Strengthening Women Parliamentarians Media Skills '},
{name: 'Student Leaders Program'},
{name: 'Support for Training, Advocacy and Networking for Development (STAND) program'},
{name: 'Supporting Election Monitoring Innovation in MENA Region'},
{name: 'SustainOman'},
{name: 'Terana: Strengthening Leaders: Equipping Organizations and Enabling Public Discourse'},
{name: 'The Protection Project'},
{name: 'Towards Environmental Advocacy'},
{name: 'Trade/WTO Seminars'},
{name: 'Tunisia Youth Media Network'},
{name: 'US-Middle East Partnership for Breast Cancer Awareness and Research'},
{name: 'US-Saudi Forum on Social Entrepreneurship'},
{name: 'Voter Ownership & Increasing Civic Engagement (VOICE) Project'},
{name: 'West Bank/Gaza Political Reform and Media Program'},
{name: 'WILpower (Women In the Law)'},
{name: 'Women Against Corruption and for Women’s Participation'},
{name: 'Women and Municipalities: A Platform for Political Participation'},
{name: 'Women in Technology (WIT)'},
{name: 'Women*777*s Enterprise for Sustainability (WES)'},
   {name: 'Women*777*s Literacy in Morocco (ALEF)'},
{name: 'Women*777*s Rights and Kuwaiti Family Law Weekly Article Series '},
   {name: 'Women*777*s Rights in Kuwaiti Personal Status Law and Bahraini Judicial Rulings '},
{name: 'Women*777*s Rights in the Middle East and North Africa'},
   {name: 'Young Women Leaders Program'},
   {name: 'Youth and Democracy Reform in Yemen '},
   {name: 'Youth Economic Development Initiative'},
   {name: 'Youth Learning for Change'},
   {name: 'Youth Political Awareness'},
   {name: 'إعلام إجتماعي | حراك إجتماعي'},
   {name: 'تحسين المشاريع المقدمة من مؤسسات التمويل الأصغر'},
   {name: 'تعزيز أصوات الشباب والنساء في المشاركة السياسية  خلال المرحلة الانتقالية'}
])