resources = Resource.create([



                                {nid: 2031, tnid: 0,
                                 language: '1',
                                 title: 'Advancing Civic Engagement in Tunisia and Global Citizen Corps (GCC)',
                                 body: '',
                                 orgname: 'Mercy Corps',
                                 mepi_project: '',
                                 training_event: '',
                                 presenter: '',
                                 partner_orgs: '',
                                 website: '' },

                                {nid: 2036, tnid: 0,
                                 language: '1',
                                 title: '1.1: Approaches to Learning Presentation',
                                 body: '<p>This brief, introductory presentation about Global Citizen Corps describes five main components of the program, which accompanies the handouts in this series. Components include student-centered learning, multiple intelligences, experiential learning, peer-to-peer mobilization and awakening the critical consciousness. The ideal ages of participants are provided in each of the TOT training files and range from 10-29.</p>',
                                 focus_youth: 1,
                                 orgname: 'Mercy Corps',
                                 mepi_project: 'Advancing Civic Engagement in Tunisia and Global Citizen Corps (GCC)',
                                 training_event: '',
                                 presenter: '',
                                 partner_orgs: '',
                                 materialtype_id: 5,
                                 number_pages: 6,
                                 website: '' },

                                {nid: 2041, tnid: 0,
                                 language: '1',
                                 title: '1.1: Approaches to Learning Handout',
                                 body: '<p>This brief handout focuses on approaches to learning, such as student-centered learning, engaging multiple intelligence, experiential learning and peer-to-peer learning. An overview of the program also is available: <a href=*777*http://maktabatmepi.org/content/11-approaches-learning-presentation*777*>http://maktabatmepi.org/content/11-approaches-learning-presentation</a>.</p>',
                                 focus_youth: 1,
                                 orgname: 'Mercy Corps',
                                 mepi_project: 'Advancing Civic Engagement in Tunisia and Global Citizen Corps (GCC)',
                                 training_event: '',
                                 presenter: '',
                                 partner_orgs: '',
                                 materialtype_id: 3,
                                 number_pages: 1,
                                 website: '' },

                                {nid: 2046, tnid: 0,
                                 language: '1',
                                 title: '1.1: Traits of a Trainer',
                                 body: '<p>This brief handout highlights traits of a good facilitator, including knowing content, entertaining, adapting and keeping focused on time. An overview of the program also is available: <a href=*777*http://maktabatmepi.org/content/11-approaches-learning-presentation*777*>http://maktabatmepi.org/content/11-approaches-learning-presentation</a>.</p>',
                                 focus_youth: 1,
                                 orgname: 'Mercy Corps',
                                 mepi_project: 'Advancing Civic Engagement in Tunisia and Global Citizen Corps (GCC)',
                                 training_event: '',
                                 presenter: '',
                                 partner_orgs: '',
                                 materialtype_id: 3,
                                 number_pages: 1,
                                 website: '' },

                                {nid: 2051, tnid: 0,
                                 language: '1',
                                 title: '1.2: Intros and Code of Conduct',
                                 body: '<p>This resource for trainers focuses on how to present a code of conduct for building a group. It provides summary, topic overview, learning objectives and key messages. It also includes lesson procedures and specific suggestions and definitions. The ideal ages of participants are between 10-29. An overview of the program also is available: <a href=*777*http://maktabatmepi.org/content/11-approaches-learning-presentation*777*>http://maktabatmepi.org/content/11-approaches-learning-presentation</a>.</p>',
                                 focus_youth: 1,
                                 orgname: 'Mercy Corps',
                                 mepi_project: 'Advancing Civic Engagement in Tunisia and Global Citizen Corps (GCC)',
                                 training_event: '',
                                 presenter: '',
                                 partner_orgs: '',
                                 materialtype_id: 1,
                                 number_pages: 5,
                                 website: '' },

                                {nid: 2056, tnid: 0,
                                 language: '1',
                                 title: '1.3: Ice Breakers and Energizers',
                                 body: '<p>This overview of ice breakers and energizers gives instructions for 40 activities, such as the map game, where participants pin the location of their birth on a map; creative name tags, where participants decorate their tags with hobbies and pictures; and the four facts game, where participants try to guess what*777*s not true. An overview of the program also is available: <a href=*777*http://maktabatmepi.org/content/11-approaches-learning-presentation*777*>http://maktabatmepi.org/content/11-approaches-learning-presentation</a>.</p>',
                                 focus_youth: 1,
                                 orgname: 'Mercy Corps',
                                 mepi_project: 'Advancing Civic Engagement in Tunisia and Global Citizen Corps (GCC)',
                                 training_event: '',
                                 presenter: '',
                                 partner_orgs: '',
                                 materialtype_id: 3,
                                 number_pages: 6,
                                 website: '' },

                                {nid: 2061, tnid: 0,
                                 language: '1',
                                 title: '2.1: Leadership Compass',
                                 body: '<p>This resource for trainers focuses on the idea of a leadership compass, helping participants to identify styles of leadership and the importance of having diversity of leadership in a group. Included is a topic overview, learning objectives and specific lesson procedures. The ideal ages of participants are between 19-29. An overview of the program also is available: <a href=*777*http://maktabatmepi.org/content/11-approaches-learning-presentation*777*>http://maktabatmepi.org/content/11-approaches-learning-presentation</a>.</p>',
                                 focus_youth: 1,
                                 orgname: 'Mercy Corps',
                                 mepi_project: 'Advancing Civic Engagement in Tunisia and Global Citizen Corps (GCC)',
                                 training_event: '',
                                 presenter: '',
                                 partner_orgs: '',
                                 materialtype_id: 1,
                                 number_pages: 8,
                                 website: '' },

                                {nid: 2066, tnid: 0,
                                 language: '1',
                                 title: '3.3: Public Speaking for TOT',
                                 body: '<p>This resource for trainers focuses on public speaking and aims to help improve students*777* oral persuasion techniques by understanding the appropriate speaking skills. Included is a topic overview, learning objectives and lesson procedures. The ideal ages of participants are between 19-29. An overview of the program also is available: <a href=*777*http://maktabatmepi.org/content/11-approaches-learning-presentation*777*>http://maktabatmepi.org/content/11-approaches-learning-presentation</a>.</p>',
                                 focus_youth: 1,
                                 orgname: 'Mercy Corps',
                                 mepi_project: 'Advancing Civic Engagement in Tunisia and Global Citizen Corps (GCC)',
                                 training_event: '',
                                 presenter: '',
                                 partner_orgs: '',
                                 materialtype_id: 1,
                                 number_pages: 4,
                                 website: '' },

                                {nid: 2071, tnid: 0,
                                 language: '1',
                                 title: '3.3: Public Speaking Presentation',
                                 body: '<p>This presentation on public speaking focuses on overcoming anxiety, preparation, speaker*777*s outline, elements of vocal delivery and tips for what to do during the speech. An overview of the program also is available: <a href=*777*http://maktabatmepi.org/content/11-approaches-learning-presentation*777*>http://maktabatmepi.org/content/11-approaches-learning-presentation</a>.</p>',
                                 focus_youth: 1,
                                 orgname: 'Mercy Corps',
                                 mepi_project: 'Advancing Civic Engagement in Tunisia and Global Citizen Corps (GCC)',
                                 training_event: '',
                                 presenter: '',
                                 partner_orgs: '',
                                 materialtype_id: 5,
                                 number_pages: 12,
                                 website: '' },

                                {nid: 2076, tnid: 0,
                                 language: '1',
                                 title: '3.3: Tips for Public Speaking',
                                 body: '<p>This handout provides tips for public speaking, including body language, voice/speech, content/message and what to do if you get nervous. An overview of the program also is available: <a href=*777*http://maktabatmepi.org/content/11-approaches-learning-presentation*777*>http://maktabatmepi.org/content/11-approaches-learning-presentation</a>.</p>',
                                 focus_youth: 1,
                                 orgname: 'Mercy Corps',
                                 mepi_project: 'Advancing Civic Engagement in Tunisia and Global Citizen Corps (GCC)',
                                 training_event: '',
                                 presenter: '',
                                 partner_orgs: '',
                                 materialtype_id: 3,
                                 number_pages: 1,
                                 website: '' },

                                {nid: 2081, tnid: 0,
                                 language: '1',
                                 title: '2.3: Tallest Tower Activity',
                                 body: '<p>This resource for trainers focuses on the *777*tallest tower*777* team-building activity, which highlights the importance of effectively working as a team, utilizing non-verbal communication and harnessing creativity and problem-solving skills. Included is a topic overview, learning objectives and lesson procedures. The ideal ages of participants are between 15-29. An overview of the program also is available: http://maktabatmepi.org/content/11-approaches-learning-presentation.</p>',
                                 focus_youth: 1,
                                 orgname: 'Mercy Corps',
                                 mepi_project: 'Advancing Civic Engagement in Tunisia and Global Citizen Corps (GCC)',
                                 training_event: '',
                                 presenter: '',
                                 partner_orgs: '',
                                 materialtype_id: 1,
                                 number_pages: 2,
                                 website: '' },

                                {nid: 2086, tnid: 0,
                                 language: '1',
                                 title: 'Home-Based Businesses - Presentation',
                                 body: '<p>This slide presentation was used for an Institute of International Education workshop that focused on home-based businesses, part of the Women*777*s Enterprise for Sustainability (WES) program.</p>',
                                 orgname: 'Institute of International Education (IIE)',
                                 mepi_project: 'Women*777*s Enterprise for Sustainability (WES)',
                                 training_event: '',
                                 presenter: '',
                                 partner_orgs: '',
                                 materialtype_id: 5,
                                 number_pages: 116,
                                 website: '' },

                                {nid: 2091, tnid: 0,
                                 language: '1',
                                 title: 'E-Commerce - Presentation',
                                 body: '<p>This slide presentation was used for an Institute of International Education workshop that focused on e-commerce, part of the Women*777*s Enterprise for Sustainability (WES) program.</p>',
                                 orgname: 'Institute of International Education (IIE)',
                                 mepi_project: 'Women*777*s Enterprise for Sustainability (WES)',
                                 training_event: '',
                                 presenter: '',
                                 partner_orgs: '',
                                 materialtype_id: 5,
                                 number_pages: 86,
                                 website: '' },

                                {nid: 2096, tnid: 0,
                                 language: '1',
                                 title: 'Social Media for Women Entrepreneurs - Presentation',
                                 body: '<p>This slide presentation was used for an Institute of International Education workshop that focused on social media for women entrepreneurs, part of the Women*777*s Enterprise for Sustainability (WES) program.</p>',
                                 orgname: 'Institute of International Education (IIE)',
                                 mepi_project: 'Women*777*s Enterprise for Sustainability (WES)',
                                 training_event: '',
                                 presenter: '',
                                 partner_orgs: '',
                                 materialtype_id: 5,
                                 website: '' },

                                {nid: 2106, tnid: 1402,
                                 language: '1',
                                 title: 'Tunisian Election Law Handbook for Lawyers',
                                 body: '<p>The comprehensive *777*Tunisian Election Law Handbook for Lawyers*777* describes and explains the country’s legal provisions surrounding electoral conduct. The handbook provides advice on applying Tunisia’s new Election Law and presents Tunisian lawyers with guidance on substantive law and procedures from the Constituent Assembly. The handbook also highlights potential areas of dispute and legal strategies in assisting citizens on election legal issues.</p>',
                                 orgname: 'American Bar Association (ABA) ',
                                 mepi_project: 'ABA Rule of Law Initiative (ABA ROLI)',
                                 training_event: '',
                                 presenter: '',
                                 partner_orgs: 'Tunisian Bar Association (TBA) ',
                                 materialtype_id: 3,
                                 number_pages: 65,
                                 website: '' },

                                {nid: 2111, tnid: 0,
                                 language: '1',
                                 title: 'Entrepreneurship Trainers Manual ',
                                 body: '<p>This training manual provides a summary of 14 modules for a entreprenuership course, along with a summary of concepts and discussion points. Topics include starting a business, strategic planning, business plans, business operations, marketing, communication, finance, risk and more. Brainstorming exercises and quizes are included.</p>',
                                 orgname: 'Institute of International Education (IIE)',
                                 mepi_project: 'Women*777*s Enterprise for Sustainability (WES)',
                                 training_event: '',
                                 presenter: 'Widad El Hanaf',
                                 partner_orgs: '',
                                 materialtype_id: 1,
                                 number_pages: 138,
                                 website: '' },

                                {nid: 2116, tnid: 0,
                                 language: '1',
                                 title: 'Civic Education Module: Separation of Powers',
                                 body: '<p>This resource from Creative Associates*777* Voter Ownership &amp; Increasing Civic Engagement (VOICE) Project is a civic education module for teaching separation of powers.</p>',
                                 orgname: 'Creative Associates International',
                                 mepi_project: 'Voter Ownership & Increasing Civic Engagement (VOICE) Project',
                                 training_event: '',
                                 presenter: '',
                                 partner_orgs: 'Libyan Association for Management and Human Resources Development (LAMHARD)',
                                 materialtype_id: 1,
                                 number_pages: 1,
                                 website: '' },

                                {nid: 2121, tnid: 0,
                                 language: '1',
                                 title: 'Civic Education Module: Human Rights',
                                 body: '<p>This resource from Creative Associates*777* Voter Ownership &amp; Increasing Civic Engagement (VOICE) Project is a civic education module for teaching human rights.</p>',
                                 orgname: 'Creative Associates International',
                                 mepi_project: 'Voter Ownership & Increasing Civic Engagement (VOICE) Project',
                                 training_event: '',
                                 presenter: '',
                                 partner_orgs: 'Libyan Association for Management and Human Resources Development (LAMHARD)',
                                 materialtype_id: 1,
                                 number_pages: 1,
                                 website: '' },

                                {nid: 2126, tnid: 0,
                                 language: '1',
                                 title: 'Civic Education Module: Gender',
                                 body: '<p>This resource from Creative Associates*777* Voter Ownership &amp; Increasing Civic Engagement (VOICE) Project is a civic education module for teaching about gender issues.</p>',
                                 focus_women: 1,
                                 orgname: 'Creative Associates International',
                                 mepi_project: 'Voter Ownership & Increasing Civic Engagement (VOICE) Project',
                                 training_event: '',
                                 presenter: '',
                                 partner_orgs: 'Libyan Association for Management and Human Resources Development (LAMHARD)',
                                 materialtype_id: 1,
                                 number_pages: 5,
                                 website: '' },

                                {nid: 2131, tnid: 0,
                                 language: '1',
                                 title: 'Civic Education Module: Freedom of Speech',
                                 body: '<p>This resource from Creative Associates*777* Voter Ownership &amp; Increasing Civic Engagement (VOICE) Project is a civic education module for teaching about freedom of speech.</p>',
                                 orgname: 'Creative Associates International',
                                 mepi_project: 'Voter Ownership & Increasing Civic Engagement (VOICE) Project',
                                 training_event: '',
                                 presenter: '',
                                 partner_orgs: 'Libyan Association for Management and Human Resources Development (LAMHARD)',
                                 materialtype_id: 1,
                                 number_pages: 1,
                                 website: '' },

                                {nid: 2136, tnid: 0,
                                 language: '1',
                                 title: 'Civic Education Module: Electoral Process',
                                 body: '<p>This resource from Creative Associates*777* Voter Ownership &amp; Increasing Civic Engagement (VOICE) Project is a civic education module for teaching about the electoral process.</p>',
                                 orgname: 'Creative Associates International',
                                 mepi_project: 'Voter Ownership & Increasing Civic Engagement (VOICE) Project',
                                 training_event: '',
                                 presenter: '',
                                 partner_orgs: 'Libyan Association for Management and Human Resources Development (LAMHARD)',
                                 materialtype_id: 1,
                                 number_pages: 5,
                                 website: '' },

                                {nid: 2141, tnid: 0,
                                 language: '1',
                                 title: 'Civic Education Module: Constitution',
                                 body: '<p>This resource from Creative Associates*777* Voter Ownership &amp; Increasing Civic Engagement (VOICE) Project is a civic education module for teaching about the constitution.</p>',
                                 orgname: 'Creative Associates International',
                                 mepi_project: 'Voter Ownership & Increasing Civic Engagement (VOICE) Project',
                                 training_event: '',
                                 presenter: '',
                                 partner_orgs: 'Libyan Association for Management and Human Resources Development (LAMHARD)',
                                 materialtype_id: 1,
                                 number_pages: 1,
                                 website: '' },

                                {nid: 2146, tnid: 0,
                                 language: '1',
                                 title: 'Civic Education Module: Citizenship',
                                 body: '<p>This resource from Creative Associates*777* Voter Ownership &amp; Increasing Civic Engagement (VOICE) Project is a civic education module for teaching about citizenship.</p>',
                                 orgname: 'Creative Associates International',
                                 mepi_project: 'Voter Ownership & Increasing Civic Engagement (VOICE) Project',
                                 training_event: '',
                                 presenter: '',
                                 partner_orgs: 'Libyan Association for Management and Human Resources Development (LAMHARD)',
                                 materialtype_id: 1,
                                 number_pages: 1,
                                 website: '' },

                                {nid: 2166, tnid: 0,
                                 language: '1',
                                 title: '1 - Optimize Your Social Media Accounts (graphically)',
                                 body: '<p>This presentation describes building blocks for optimizing an organization*777*s social media presence related to social media accounts. Topics include cover photos and avatars, photos on Facebook, Twitter and Google+, Instagram and other sites, milestones sections and tabs sections.</p>',
                                 orgname: 'Think Media Labs',
                                 mepi_project: 'Enhancing CSO National Dialogue and Collaboration via Social Media',
                                 training_event: '',
                                 presenter: '',
                                 partner_orgs: '',
                                 materialtype_id: 5,
                                 website: '' },

                                {nid: 2171, tnid: 0,
                                 language: '1',
                                 title: '2 - Online Presence of Founders',
                                 body: '<p>This presentation describes aspects of building a social media presence, focusing on the online presence of founders. The emphasis is on the importance of founders and management being active on social media. Tips highlight the idea that people engage more with people than with organizations.</p>',
                                 orgname: 'Think Media Labs',
                                 mepi_project: 'Enhancing CSO National Dialogue and Collaboration via Social Media',
                                 training_event: '',
                                 presenter: '',
                                 partner_orgs: '',
                                 materialtype_id: 5,
                                 website: '' },

                                {nid: 2176, tnid: 0,
                                 language: '1',
                                 title: '3 - CSO LinkedIn Corporate Pages',
                                 body: '<p>This presentation provides detailed instructions for creating a CSO corporate page and Showcase pages on LinkedIn. It &nbsp;describes various outreach techniques, such as how best to utilize the Showcase pages, and it highlights statistics about LinkedIn use in Lebanon.</p>',
                                 orgname: 'Think Media Labs',
                                 mepi_project: 'Enhancing CSO National Dialogue and Collaboration via Social Media',
                                 training_event: '',
                                 presenter: '',
                                 partner_orgs: '',
                                 materialtype_id: 5,
                                 website: '' },

                                {nid: 2181, tnid: 0,
                                 language: '1',
                                 title: '4 - Relate CSOs Content to Trends',
                                 body: '<p>This presentation recommends that when trends are relevant to the CSO*777*s objectives, it is important to share and create related content for promotion. To help develop ideas, Facebook*777*s *777*Trending*777* feature is highlighted. In addition, the presentation describes the changing dynamics of online advertising, real-time marketing, categories of content and more.</p>',
                                 orgname: 'Think Media Labs',
                                 mepi_project: 'Enhancing CSO National Dialogue and Collaboration via Social Media',
                                 training_event: '',
                                 presenter: '',
                                 partner_orgs: '',
                                 materialtype_id: 5,
                                 website: '' },

                                {nid: 2186, tnid: 0,
                                 language: '1',
                                 title: '7 - Social Media Tools',
                                 body: '<p>This presentation on social media tools for CSOs highlights several options, including TweetDeck, Hootsuite, Iconosquare, KeyHole and TweetReach.</p>',
                                 orgname: 'Think Media Labs',
                                 mepi_project: 'Enhancing CSO National Dialogue and Collaboration via Social Media',
                                 training_event: '',
                                 presenter: '',
                                 partner_orgs: '',
                                 materialtype_id: 5,
                                 number_pages: 26,
                                 website: '' },

                                {nid: 2191, tnid: 0,
                                 language: '1',
                                 title: '6 - Social Media Ads',
                                 body: '<p>This presentation highlights the process of using social media ads to promote CSOs on Facebook, Twitter and Google. It gives tips on budgeting, visuals and interface.</p>',
                                 orgname: 'Think Media Labs',
                                 mepi_project: 'Enhancing CSO National Dialogue and Collaboration via Social Media',
                                 training_event: '',
                                 presenter: '',
                                 partner_orgs: '',
                                 materialtype_id: 5,
                                 number_pages: 55,
                                 website: '' },

                                {nid: 2196, tnid: 0,
                                 language: '1',
                                 title: '5 - What is Outreach Marketing?',
                                 body: '<p>This presentation focuses on Twitter as an outreach and marketing tool, providing tips for using TweetDeck dashboards, outreach search and keyword list searches. It provides examples of using Twitter to conduct outreach to journalists, politicians, online communities and other CSOs.</p>',
                                 orgname: 'Think Media Labs',
                                 mepi_project: 'Enhancing CSO National Dialogue and Collaboration via Social Media',
                                 training_event: '',
                                 presenter: '',
                                 partner_orgs: '',
                                 materialtype_id: 5,
                                 number_pages: 66,
                                 website: '' },

                                {nid: 2201, tnid: 0,
                                 language: '1',
                                 title: '8 - KPIs and ROI for Setting Expectations from your Agency of Record',
                                 body: '<p>This presentation focuses on using key performance indicators (KPIs) and return on investment (ROI) to set organizational expectations. It highlights why a framework is important, including intent, definitions of metrics and setting benchmarks. It then provides guidelines for introducing a framework and for defining KPIs and ROI.</p>',
                                 orgname: 'Think Media Labs',
                                 mepi_project: 'Enhancing CSO National Dialogue and Collaboration via Social Media',
                                 training_event: '',
                                 presenter: '',
                                 partner_orgs: '',
                                 materialtype_id: 5,
                                 number_pages: 40,
                                 website: '' },

                                {nid: 2206, tnid: 0,
                                 language: '1',
                                 title: '9 - Crisis Management',
                                 body: '<p>This presentation focuses on outreach crises - emergency situations that occur all over an organization*777*s social media platforms. It discusses three aspects to handling these situations - pre-crisis, crisis event and post-crisis.</p>',
                                 orgname: 'Think Media Labs',
                                 mepi_project: 'Enhancing CSO National Dialogue and Collaboration via Social Media',
                                 training_event: '',
                                 presenter: '',
                                 partner_orgs: '',
                                 materialtype_id: 5,
                                 number_pages: 35,
                                 website: '' },

                                {nid: 2211, tnid: 0,
                                 language: '1',
                                 title: 'Create a Company Page',
                                 body: '<p>This presentation describes the benefits of creating a LinkedIn *777*Company Page*777* for CSOs, including tools to encourage supporters to promote the organization*777*s cause, find board members and volunteers, and locate staff.</p>',
                                 orgname: 'Think Media Labs',
                                 mepi_project: 'Enhancing CSO National Dialogue and Collaboration via Social Media',
                                 training_event: '',
                                 event_date: DateTime.new(2014,11,13),
                                 presenter: '',
                                 partner_orgs: '',
                                 materialtype_id: 5,
                                 number_pages: 29,
                                 website: '' },

                                {nid: 2216, tnid: 0,
                                 language: '1',
                                 title: 'How to Build a Powerful Network Using LinkedIn',
                                 body: '<p>This presentation provides tips for improving your LinkedIn network and connections. It emphasizes the value of being selective in building a network, using clusters, groups and advanced search to find additional&nbsp; contacts, and how to organize your networks with tags.</p>',
                                 orgname: 'Think Media Labs',
                                 mepi_project: 'Enhancing CSO National Dialogue and Collaboration via Social Media',
                                 training_event: '',
                                 event_date: DateTime.new(2014,11,13),
                                 presenter: '',
                                 partner_orgs: '',
                                 materialtype_id: 5,
                                 number_pages: 29,
                                 website: '' },

                                {nid: 2226, tnid: 0,
                                 language: '1',
                                 title: 'Checklist for Daily Content Shared, Replying to Questions, and Inbox Message',
                                 body: '<p>This handout provides a checklist for daily content sharing, including tips for posting and publishing on YouTube, Facebook and Twitter.</p>',
                                 orgname: 'Think Media Labs',
                                 mepi_project: 'Enhancing CSO National Dialogue and Collaboration via Social Media',
                                 training_event: '',
                                 presenter: '',
                                 partner_orgs: '',
                                 materialtype_id: 3,
                                 number_pages: 2,
                                 website: '' },

                                {nid: 2231, tnid: 0,
                                 language: '1',
                                 title: 'Daily Outreach Checklist',
                                 body: '<p>This handout provides structure for daily outreach efforts, including noting the number of requested outreach efforts per day and the target audience. It also provides space for remarks, as a reminder.</p>',
                                 orgname: 'Think Media Labs',
                                 mepi_project: 'Enhancing CSO National Dialogue and Collaboration via Social Media',
                                 training_event: '',
                                 presenter: '',
                                 partner_orgs: '',
                                 materialtype_id: 3,
                                 number_pages: 2,
                                 website: '' },

                                {nid: 2236, tnid: 0,
                                 language: '1',
                                 title: 'Optimizing Social Media Profile of CSO',
                                 body: '<p>This handout provides a checklist for optimizing social media profiles, including pre-publishing, posts, publishing and post publishing tasks.</p>',
                                 orgname: 'Think Media Labs',
                                 mepi_project: 'Enhancing CSO National Dialogue and Collaboration via Social Media',
                                 training_event: '',
                                 presenter: '',
                                 partner_orgs: '',
                                 materialtype_id: 3,
                                 number_pages: 3,
                                 website: '' },

                                {nid: 2241, tnid: 0,
                                 language: '1',
                                 title: 'Optimizing Social Media Profile of Founders and Management of CSO ',
                                 body: '<p>This handout provides a checklist for optimizing the social media profile of CSO founders and management with profile setup tasks.</p>',
                                 orgname: 'Think Media Labs',
                                 mepi_project: 'Enhancing CSO National Dialogue and Collaboration via Social Media',
                                 training_event: '',
                                 presenter: '',
                                 partner_orgs: '',
                                 materialtype_id: 3,
                                 number_pages: 1,
                                 website: '' },

                                {nid: 2246, tnid: 0,
                                 language: '1',
                                 title: 'Weekly Master Checklist',
                                 body: '<p>This brief handout provides a weekly master checklist for tracking content topic and type of posts, person responsible, date and social media outlet.</p>',
                                 orgname: 'Think Media Labs',
                                 mepi_project: 'Enhancing CSO National Dialogue and Collaboration via Social Media',
                                 training_event: '',
                                 presenter: '',
                                 partner_orgs: '',
                                 materialtype_id: 3,
                                 number_pages: 1,
                                 website: '' },

                                {nid: 2256, tnid: 0,
                                 language: '1',
                                 title: 'The Press Release: What the Media Want to Know About You',
                                 body: '<p>This introductory presentation for CSOs highlights reasons for needing the media and an overview of news, journalists and who to reach out to. It also describes the structure and sections of press releases.</p>',
                                 orgname: 'International Research & Exchanges Board (IREX)',
                                 mepi_project: 'Social Media | Social Action for Good Governance',
                                 training_event: '',
                                 presenter: '',
                                 partner_orgs: '',
                                 materialtype_id: 5,
                                 number_pages: 15,
                                 website: '' },

                                {nid: 2286, tnid: 0,
                                 language: '1',
                                 title: 'Students Civic Engagement Training Curriculum',
                                 body: '<p>This manual provides six training modules focused on leadership and volunteerism to promote workforce and community engagement through experiential learning. While the module progression is designed to build a comprehensive leadership program, each module can be used as a stand-alone two-hour program. Each module includes a one-page overview: module background, objectives, expected application, data collection plan, pre-training preparation and outline.</p>',
                                 focus_youth: 1,
                                 orgname: 'World Learning',
                                 mepi_project: 'Promoting Education, Altruism, and Civic Engagement (PEACE)',
                                 training_event: '',
                                 presenter: '',
                                 partner_orgs: '',
                                 materialtype_id: 1,
                                 number_pages: 77,
                                 website: '' },

                                {nid: 2316, tnid: 0,
                                 language: '1',
                                 title: 'Cooperative Advocacy',
                                 body: '<p>This manual is meant to serve as an introduction to cooperative advocacy for organizations interested in strengthening their knowledge and promoting collaboration and sustainability within the civic sector. It is one of a series of 12 manuals that was developed as part of the STAND program, which aims to build the capacity of non-profit organizations in Kuwait and the region. The toolkit is available in <a href=*777*http://www.socialprograms.envearth.com/stand-manual-03-cooperative-advocacy/*777*>English</a> and <a href=*777*http://www.socialprograms.envearth.com/stand-manual-04-cooperative-advocacy-ar/*777*>Arabic</a>. In addition, a <a href=*777*https://www.youtube.com/watch?v=SAjsZTYRy4Q&amp;index=9&amp;list=PLJv7VOmQDSjCiufqB6vBimeuDu0WG5-qy*777*>brief introductory video</a> is available in English, with Arabic subtitles.</p>',
                                 orgname: 'Partners for Democratic Change',
                                 mepi_project: 'Support for Training, Advocacy and Networking for Development (STAND) program',
                                 training_event: '',
                                 presenter: '',
                                 partner_orgs: 'en.v',
                                 materialtype_id: 3,
                                 number_pages: 13,
                                 website: '' },

                                {nid: 2321, tnid: 0,
                                 language: '1',
                                 title: 'Strategic Planning for NonProfit Organizations',
                                 body: '<p>This manual is meant to serve as an introduction to strategic planning for organizations interested in strengthening their knowledge and promoting collaboration and sustainability within the civic sector. It is one of a series of 12 manuals that was developed as part of the STAND program, which aims to build the capacity of non-profit organizations in Kuwait and the region. It also is available online in <a href=*777*http://www.socialprograms.envearth.com/stand-manual-03-strategic-planning/*777*>English</a> and <a href=*777*http://www.socialprograms.envearth.com/stand-manual-strategic-planning-ar/*777*>Arabic</a>. In addition, a <a href=*777*https://www.youtube.com/watch?v=NbGxQYDJqYc&amp;list=PLJv7VOmQDSjCiufqB6vBimeuDu0WG5-qy&amp;index=10*777*>brief introductory video</a> is available in English, with Arabic subtitles.</p>',
                                 orgname: 'Partners for Democratic Change',
                                 mepi_project: 'Support for Training, Advocacy and Networking for Development (STAND) program',
                                 training_event: '',
                                 presenter: '',
                                 partner_orgs: 'en.v',
                                 materialtype_id: 3,
                                 number_pages: 16,
                                 website: '' },

                                {nid: 2326, tnid: 0,
                                 language: '1',
                                 title: 'Leadership for Third Sector Organizations',
                                 body: '<p>This manual is meant to serve as an introduction to leadership for organizations interested in strengthening their knowledge and promoting collaboration and sustainability within the civic sector. It is one of a series of 12 manuals that was developed as part of the STAND program, which aims to build the capacity of non-profit organizations in Kuwait and the region. It also is available online in <a href=*777*http://www.socialprograms.envearth.com/stand-manual-02-leadership/*777*>English</a> and <a href=*777*http://www.socialprograms.envearth.com/stand-manual-leadership-ar/ *777*>Arabic</a>. In addition, a <a href=*777*https://www.youtube.com/watch?v=Ik-7WDKOIws&amp;index=11&amp;list=PLJv7VOmQDSjCiufqB6vBimeuDu0WG5-qy*777*>brief introductory video</a> is available in English, with Arabic subtitles.</p>',
                                 orgname: 'Partners for Democratic Change',
                                 mepi_project: 'Support for Training, Advocacy and Networking for Development (STAND) program',
                                 training_event: '',
                                 presenter: '',
                                 partner_orgs: 'en.v',
                                 materialtype_id: 3,
                                 number_pages: 12,
                                 website: '' },

                                {nid: 2331, tnid: 0,
                                 language: '1',
                                 title: 'NGO Governance',
                                 body: '<p>This manual is meant to serve as an introduction to NGO governance for organizations interested in strengthening their knowledge and promoting collaboration and sustainability within the civic sector. It is one of a series of 12 manuals that was developed as part of the STAND program, which aims to build the capacity of non-profit organizations in Kuwait and the region. It also is available online in <a href=*777*http://www.socialprograms.envearth.com/stand-manual-ngo-governance-en/*777*>English</a> and <a href=*777*http://www.socialprograms.envearth.com/stand-manual-ngo-governance-ar/*777*>Arabic</a>. Also, a <a href=*777*https://www.youtube.com/watch?v=RzmT51D9rw0&amp;list=PLJv7VOmQDSjCiufqB6vBimeuDu0WG5-qy&amp;index=12*777*>brief introductory video</a> is available in English with Arabic subtitles.</p>',
                                 orgname: 'Partners for Democratic Change',
                                 mepi_project: 'Support for Training, Advocacy and Networking for Development (STAND) program',
                                 training_event: '',
                                 presenter: '',
                                 partner_orgs: 'en.v',
                                 materialtype_id: 3,
                                 number_pages: 12,
                                 website: '' },

                                {nid: 2336, tnid: 0,
                                 language: '1',
                                 title: 'Human Resource Management',
                                 body: '<p>This manual is meant to serve as an introduction to HR management for organizations interested in strengthening their knowledge and promoting collaboration and sustainability within the civic sector. It is one of a series of 12 manuals that was developed as part of the STAND program, which aims to build the capacity of non-profit organizations in Kuwait and the region. It also is available online in <a href=*777*http://www.socialprograms.envearth.com/stand-manual-12-hr-management/*777*>English</a> and <a href=*777*http://www.socialprograms.envearth.com/stand-manual-hr-management-ar*777*>Arabic</a>. In addition, a <a href=*777*https://www.youtube.com/watch?v=X9btnkbpxrY&amp;index=1&amp;list=PLJv7VOmQDSjCiufqB6vBimeuDu0WG5-qy*777*>brief introductory video</a> is available in English with Arabic subtitles.</p>',
                                 orgname: 'Partners for Democratic Change',
                                 mepi_project: 'Support for Training, Advocacy and Networking for Development (STAND) program',
                                 training_event: '',
                                 presenter: '',
                                 partner_orgs: 'en.v',
                                 materialtype_id: 3,
                                 number_pages: 17,
                                 website: '' },

                                {nid: 2341, tnid: 0,
                                 language: '1',
                                 title: 'Financial Management for Non-Profit Organizations',
                                 body: '<p>This manual is meant to serve as an introduction to financial management for organizations interested in strengthening their knowledge and promoting collaboration and sustainability within the civic sector. It is one of a series of 12 manuals that was developed as part of the STAND program, which aims to build the capacity of CSOs in Kuwait and the region. It also is available online in <a href=*777*http://www.socialprograms.envearth.com/stand-manual-11-financial-management/*777*>English</a> and <a href=*777*http://www.socialprograms.envearth.com/stand-manual-financial-management-ar/*777*>Arabic</a>. In addition, a <a href=*777*https://www.youtube.com/watch?v=3u5hn2ewCd4&amp;list=PLJv7VOmQDSjCiufqB6vBimeuDu0WG5-qy&amp;index=2*777*>brief introductory video</a> is available in English with Arabic subtitles.</p>',
                                 orgname: 'Partners for Democratic Change',
                                 mepi_project: 'Support for Training, Advocacy and Networking for Development (STAND) program',
                                 training_event: '',
                                 presenter: '',
                                 partner_orgs: 'en.v',
                                 materialtype_id: 3,
                                 number_pages: 16,
                                 website: '' },

                                {nid: 2346, tnid: 0,
                                 language: '1',
                                 title: 'Conflict Management ',
                                 body: '<p>This manual is meant to serve as an introduction to conflict management for organizations interested in strengthening their knowledge and promoting collaboration and sustainability within the civic sector. It is one of a series of 12 manuals that was developed as part of the STAND program, which aims to build the capacity of non-profit organizations in Kuwait and the region. It also is available online in <a href=*777*http://www.socialprograms.envearth.com/stand-manual-10-conflict-management/*777*>English</a> and <a href=*777*http://www.socialprograms.envearth.com/stand-manual-conflict-management-ar/*777*>Arabic</a>. In addition, a <a href=*777*https://www.youtube.com/watch?v=QjMSiv-j60Q&amp;index=3&amp;list=PLJv7VOmQDSjCiufqB6vBimeuDu0WG5-qy*777*>brief introductory video</a> is available in English with Arabic subtitles.</p>',
                                 orgname: 'Partners for Democratic Change',
                                 mepi_project: 'Support for Training, Advocacy and Networking for Development (STAND) program',
                                 training_event: '',
                                 presenter: '',
                                 partner_orgs: 'en.v',
                                 materialtype_id: 3,
                                 number_pages: 16,
                                 website: '' },

                                {nid: 2351, tnid: 0,
                                 language: '1',
                                 title: 'Coalition Building and Networking',
                                 body: '<p>This manual is meant to serve as an introduction to coalition building for organizations interested in strengthening their knowledge and promoting collaboration and sustainability within the civic sector. It is one of a series of 12 manuals that was developed as part of the STAND program, which aims to build the capacity of non-profit organizations in Kuwait and the region. It also is available online in <a href=*777*http://www.socialprograms.envearth.com/stand-manual-09-coalition-building/*777*>English</a> and <a href=*777*http://www.socialprograms.envearth.com/stand-manual-coalition-building-ar/*777*>Arabic</a>. In addition, a <a href=*777*https://www.youtube.com/watch?v=IpOmVqnEnVQ&amp;list=PLJv7VOmQDSjCiufqB6vBimeuDu0WG5-qy&amp;index=4*777*>brief introductory video</a> is available in English with Arabic subtitles.</p>',
                                 orgname: 'Partners for Democratic Change',
                                 mepi_project: 'Support for Training, Advocacy and Networking for Development (STAND) program',
                                 training_event: '',
                                 presenter: '',
                                 partner_orgs: 'en.v',
                                 materialtype_id: 3,
                                 number_pages: 17,
                                 website: '' },

                                {nid: 2356, tnid: 0,
                                 language: '1',
                                 title: 'Project Management for Third Sector Organizations ',
                                 body: '<p>This manual is meant to serve as an introduction to project management for organizations interested in strengthening their knowledge and promoting collaboration and sustainability within the civic sector. It is one of a series of 12 manuals that was developed as part of the STAND program, which aims to build the capacity of non-profit organizations in Kuwait and the region. It also is available online in <a href=*777*http://www.socialprograms.envearth.com/stand-manual-08-project-management/*777*>English</a> and <a href=*777*http://www.socialprograms.envearth.com/stand-manual-project-management-ar/*777*>Arabic</a>. In addition, a <a href=*777*https://www.youtube.com/watch?v=LSQ3vZXtzJM&amp;index=5&amp;list=PLJv7VOmQDSjCiufqB6vBimeuDu0WG5-qy*777*>brief introductory video</a> is available in English with Arabic subtitles.</p>',
                                 orgname: 'Partners for Democratic Change',
                                 mepi_project: 'Support for Training, Advocacy and Networking for Development (STAND) program',
                                 training_event: '',
                                 presenter: '',
                                 partner_orgs: 'en.v',
                                 materialtype_id: 3,
                                 number_pages: 13,
                                 website: '' },

                                {nid: 2361, tnid: 0,
                                 language: '1',
                                 title: 'Grant Writing ',
                                 body: '<p>This manual is meant to serve as an introduction to grant writing for organizations interested in strengthening their knowledge and promoting collaboration and sustainability within the civic sector. It is one of a series of 12 manuals that was developed as part of the STAND program, which aims to build the capacity of non-profit organizations in Kuwait and the region. It also is available online in <a href=*777*http://www.socialprograms.envearth.com/stand-manual-06-grant-writing/*777*>English</a> and <a href=*777*http://www.socialprograms.envearth.com/stand-manual-grant-writing-ar/*777*>Arabic</a>. In addition, a <a href=*777*https://www.youtube.com/watch?v=V7GBgc6T-Do&amp;list=PLJv7VOmQDSjCiufqB6vBimeuDu0WG5-qy&amp;index=6*777*>brief introductory video</a> is available in English with Arabic subtitles.</p>',
                                 orgname: 'Partners for Democratic Change',
                                 mepi_project: 'Support for Training, Advocacy and Networking for Development (STAND) program',
                                 training_event: '',
                                 presenter: '',
                                 partner_orgs: 'en.v',
                                 materialtype_id: 3,
                                 number_pages: 15,
                                 website: '' },

                                {nid: 2366, tnid: 0,
                                 language: '1',
                                 title: 'NGO Fundraising ',
                                 body: '<p>This manual is meant to serve as an introduction to NGO fundraising for organizations interested in strengthening their knowledge and promoting collaboration and sustainability within the civic sector. It is one of a series of 12 manuals that was developed as part of the STAND program, which aims to build the capacity of non-profit organizations in Kuwait and the region. It also is available online in <a href=*777*http://www.socialprograms.envearth.com/stand-manual-05-ngo-fundraising/*777*>English</a> and <a href=*777*http://www.socialprograms.envearth.com/stand-manual-05-ngo-fundraising-ar/*777*>Arabic</a>. In addition, a <a href=*777*https://www.youtube.com/watch?v=hhNWjI1J9bU&amp;list=PLJv7VOmQDSjCiufqB6vBimeuDu0WG5-qy&amp;index=8*777*>brief introductory video</a> is available in English with Arabic subtitles.</p>',
                                 orgname: 'Partners for Democratic Change',
                                 mepi_project: 'Support for Training, Advocacy and Networking for Development (STAND) program',
                                 training_event: '',
                                 presenter: '',
                                 partner_orgs: 'en.v',
                                 materialtype_id: 5,
                                 number_pages: 12,
                                 website: '' },

                                {nid: 2371, tnid: 0,
                                 language: '1',
                                 title: 'Monitoring & Evaluation for Third Sector Organizations',
                                 body: '<p>This manual is meant to serve as an introduction to monitoring and evaluation for organizations interested in strengthening their knowledge and promoting collaboration and sustainability within the civic sector. It is one of a series of 12 manuals that was developed as part of the STAND program, which aims to build the capacity of non-profit organizations in Kuwait and the region. It also is available online in <a href=*777*http://www.socialprograms.envearth.com/stand-manual-07-monitoring-evaluation*777*>English</a> and <a href=*777*http://www.socialprograms.envearth.com/stand-manual-monitoring-evaluation-ar*777*>Arabic</a>. In addition, a <a href=*777*https://www.youtube.com/watch?v=Y_z9H0alSqQ&amp;index=7&amp;list=PLJv7VOmQDSjCiufqB6vBimeuDu0WG5-qy*777*>brief introductory video</a> is available in English with Arabic subtitles.</p>',
                                 orgname: 'Partners for Democratic Change',
                                 mepi_project: 'Support for Training, Advocacy and Networking for Development (STAND) program',
                                 training_event: '',
                                 presenter: '',
                                 partner_orgs: 'en.v',
                                 materialtype_id: 3,
                                 number_pages: 16,
                                 website: '' },

                                {nid: 2381, tnid: 0,
                                 language: '1',
                                 title: 'Administrative Corruption in Lebanon: Key Features and Ways Ahead',
                                 body: '<p>This report describes a 2013 administration corruption survey, outlines the status of bribery in Lebanon and describes a proposed strategy for addressing corruption in public administrations. Both English and Arabic are included.</p>',
                                 orgname: 'Center for International Private Enterprise (CIPE)',
                                 mepi_project: 'Strengthening the Rule of Law in Lebanon through Rights Education',
                                 training_event: '',
                                 presenter: 'Dany Haddad',
                                 partner_orgs: 'Lebanese Transparency Association (LTA), Lebanon Anti-Bribery Network (LABN)',
                                 materialtype_id: 3,
                                 number_pages: 90,
                                 website: '' },

                                {nid: 2386, tnid: 0,
                                 language: '1',
                                 title: 'Access to Information: Benefits for the Private Sector',
                                 body: '<p>The objective of this report is to contribute to the debate on the importance of access to information for the private sector. It highlights laws, efforts and challenges specific to Lebanon. Both English and Arabic are included.</p>',
                                 orgname: 'Center for International Private Enterprise (CIPE)',
                                 mepi_project: 'Strengthening the Rule of Law in Lebanon through Rights Education',
                                 training_event: '',
                                 presenter: 'Dany Haddad',
                                 partner_orgs: 'Lebanese Transparency Association (LTA)',
                                 materialtype_id: 3,
                                 number_pages: 82,
                                 website: '' },

                                {nid: 2401, tnid: 0,
                                 language: '1',
                                 title: 'Social Media for Women Entrepreneurs',
                                 body: '<p>This social media curriculum resource includes a trainer*777*s guide and PowerPoint presentation, targeted at female entrepreneurs for a two-day workshop. The content focuses on using&nbsp; social media platforms (blogging, LinkedIn, Facebook, Twitter, Pinterest) and simple frameworks for integrating social media into business marketing plans. Tips are included for customizing the curriculum for specific participants.</p>',
                                 focus_women: 1,
                                 orgname: 'Institute of International Education',
                                 mepi_project: 'Women*777*s Enterprise for Sustainability (WES)',
                                 training_event: '',
                                 presenter: 'Beth Kanter',
                                 partner_orgs: '',
                                 materialtype_id: 1,
                                 number_pages: 117,
                                 website: '' },

                                {nid: 2406, tnid: 0,
                                 language: '1',
                                 title: 'Leadership PPT',
                                 body: '<p>This PowerPoint presentation focusing on leadership from IIE is available in French.</p>',
                                 focus_women: 1,
                                 orgname: 'Institute of International Education (IIE)',
                                 mepi_project: 'Women*777*s Enterprise for Sustainability (WES)',
                                 training_event: '',
                                 presenter: '',
                                 partner_orgs: '',
                                 materialtype_id: 5,
                                 number_pages: 12,
                                 website: '' },

                                {nid: 2411, tnid: 0,
                                 language: '1',
                                 title: 'Phase II Leadership Participants Guide',
                                 body: '<p>This leadership participants*777* guide from IIE is available in French.</p>',
                                 focus_women: 1,
                                 orgname: 'Institute of International Education (IIE)',
                                 mepi_project: 'Women*777*s Enterprise for Sustainability (WES)',
                                 training_event: '',
                                 presenter: '',
                                 partner_orgs: '',
                                 materialtype_id: 3,
                                 number_pages: 40,
                                 website: '' },

                                {nid: 2416, tnid: 0,
                                 language: '1',
                                 title: 'Phase II Entrepreneurship Trainer*777*s Guide',
                                 body: '<p>This entrepreneurship trainer*777*s guide from IIE is available in French.</p>',
                                 focus_women: 1,
                                 orgname: 'Institute of International Education (IIE)',
                                 mepi_project: 'Women*777*s Enterprise for Sustainability (WES)',
                                 training_event: '',
                                 presenter: '',
                                 partner_orgs: '',
                                 materialtype_id: 1,
                                 number_pages: 89,
                                 website: '' },

                                {nid: 2421, tnid: 0,
                                 language: '1',
                                 title: 'Phase II Entrepreneurship Intermediate Business Plan',
                                 body: '<p>This intermediate business plan guide from IIE is available in French.</p>',
                                 focus_women: 1,
                                 orgname: 'Institute of International Education (IIE)',
                                 mepi_project: 'Women*777*s Enterprise for Sustainability (WES)',
                                 training_event: '',
                                 presenter: '',
                                 partner_orgs: '',
                                 materialtype_id: 3,
                                 number_pages: 14,
                                 website: '' },

                                {nid: 2426, tnid: 0,
                                 language: '1',
                                 title: 'Phase II Entrepreneurship Beginning Business Plan',
                                 body: '<p>This handout supports the training files in this series and is available in Arabic.</p>',
                                 focus_women: 1,
                                 orgname: 'Institute of International Education (IIE)',
                                 mepi_project: 'Women*777*s Enterprise for Sustainability (WES)',
                                 training_event: '',
                                 presenter: '',
                                 partner_orgs: '',
                                 materialtype_id: 3,
                                 number_pages: 2,
                                 website: '' },

                                {nid: 2431, tnid: 0,
                                 language: '1',
                                 title: 'Financial Education Trainers Guide',
                                 body: '<p>This trainers guide from IIE focuses on financial education and is available in French.</p>',
                                 focus_women: 1,
                                 orgname: 'Institute of International Education (IIE)',
                                 mepi_project: 'Women*777*s Enterprise for Sustainability (WES)',
                                 training_event: '',
                                 presenter: '',
                                 partner_orgs: '',
                                 materialtype_id: 1,
                                 number_pages: 44,
                                 website: '' },

                                {nid: 2471, tnid: 0,
                                 language: '1',
                                 title: 'Middle East Regional Bankruptcy Reform Initiative Video',
                                 body: '<p>ACRLI created an introductory video about bankruptcy reform to accompany their book on the topic, <a href=*777*http://maktabatmepi.org/content/modernizing-bankruptcy-system-jordan-and-egypt*777*>Modernizing the Bankruptcy System in Jordan and Egypt</a>. The video is available in Arabic with English subtitles on <a href=*777*https://www.youtube.com/watch?v=-7pUB5SkiJs&amp;feature=player_embedded*777*>YouTube</a> and on the organization*777*s <a href=*777*http://www.arabruleoflaw.com/bankruptcyreform/?page_id=21*777*>website</a>. More information about the project is <a href=*777*http://www.arabruleoflaw.org/bankruptcyreform/*777*>online</a>.</p>',
                                 orgname: 'Arab Center for the Development of the Rule of Law and Integrity (ACRLI)',
                                 mepi_project: 'Bankruptcy Reform',
                                 training_event: '',
                                 presenter: '',
                                 partner_orgs: '',
                                 materialtype_id: 6,
                                 website: '' },

                                {nid: 2476, tnid: 0,
                                 language: '1',
                                 title: 'Modernizing the Bankruptcy System in Jordan and Egypt',
                                 body: '<p>This book is the result of an ACRLI project aimed at promoting and raising confidence in business and commerce in Egypt and Jordan. The book highlights the need to establish and activate rule of law concepts in the trade and business sectors. A <a href=*777*http://maktabatmepi.org/content/middle-east-regional-bankruptcy-reform-initiative-video*777*>related video</a> is available, and additional resources are <a href=*777*http://www.arabruleoflaw.org/bankruptcyreform*777*>online</a>. More information about the project also is available <a href=*777*http://www.arabruleoflaw.org/bankruptcyreform/*777*>on the ACRLI site</a>.</p>',
                                 orgname: 'Arab Center for the Development of the Rule of Law and Integrity (ACRLI)',
                                 mepi_project: 'Bankruptcy Reform',
                                 training_event: '',
                                 presenter: '',
                                 partner_orgs: '',
                                 materialtype_id: 3,
                                 number_pages: 384,
                                 website: '' },

                                {nid: 2516, tnid: 0,
                                 language: '1',
                                 title: 'FW: Website for safeguarding elections',
                                 body: '<p>FW: (Forward) is an informal, web-based community of civic activists, technology junkies, academics, bloggers, journalists and citizens interested in learning about and sharing new approaches and tools for safeguarding elections. The site is available in English, Arabic and French at <a href=*777*http://www.fwelections.com*777*>www.fwelections.com</a>.</p>',
                                 orgname: 'Democracy International',
                                 mepi_project: 'Supporting Election Monitoring Innovation in MENA Region ',
                                 training_event: '',
                                 presenter: '',
                                 partner_orgs: 'Github Social Coding',
                                 materialtype_id: 2,
                                 website: '' },

                                {nid: 2521, tnid: 0,
                                 language: '1',
                                 title: 'FW: Website for safeguarding elections',
                                 body: '<p>FW: (Forward) is an informal, web-based community of civic activists, technology junkies, academics, bloggers, journalists and citizens interested in learning about and sharing new approaches and tools for safeguarding elections. The site is available in English, Arabic and French at <a href=*777*http://www.fwelections.com*777*>www.fwelections.com</a>.</p>',
                                 orgname: 'Democracy International',
                                 mepi_project: 'Supporting Election Monitoring Innovation in MENA Region',
                                 training_event: '',
                                 presenter: '',
                                 partner_orgs: 'Github social Coding',
                                 materialtype_id: 2,
                                 website: '' }
                            ])